import Head from 'next/head';
import { ReactNode } from 'react';

import Header from '../../navigation/Header/Header';
import Footer from '../../navigation/Footer/Footer';

// export interface IPrimaryLayout {
//   children: ReactNode;
// }

export interface IPrimaryLayout extends React.ComponentPropsWithoutRef<'div'> {
  justify?: 'items-center' | 'items-start';
}

const PrimaryLayout: React.FC<IPrimaryLayout> = ({ children, ...divProps }) => {
  return (
    <>
      <Head>
        <title>Employee Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="md:container">{children}</main>

      <Footer />
    </>
  );
};

export default PrimaryLayout;
