import Navbar from 'components/Navbar/Navbar';
import Head from 'next/head';
import { ReactNode } from 'react';

export interface IPrimaryLayout {
    children: ReactNode
}

const PrimaryLayout: React.FC<IPrimaryLayout> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Employee Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main className="md:container">
        {children}
      </main>
    </>
  );
};

export default PrimaryLayout;
