import type { AppProps } from 'next/app';
import Head from 'next/head';
import '../assets/globals.css';
import '../assets/icons/fontawesome-5/css/all.min.css';
import PrimaryLayout from '../components/Layouts/primary/PrimaryLayout';
import { AuthProvider } from '../context/Auth/AuthContext';
import { NextPageWithLayout } from './page';

import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import 'react-datepicker/dist/react-datepicker.css';

import AOS from 'aos';
import 'aos/dist/aos.css'; // You can also use <link> for styles
import { useEffect } from 'react';
// ..

interface AppPropsWithLayout extends AppProps {
  Component: NextPageWithLayout;
}

function MyApp({ Component, pageProps }: AppPropsWithLayout) {
  const getLayout = Component.getLayout || ((page) => page);

  useEffect(() => {
    AOS.init();
  }, []);

  return (
    <>
      <Head>
        <title>Employee Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen flex flex-col">
        <AuthProvider>
          {/* <PrimaryLayout> */}
          {/* we are not using any app level layout, but using a page level layout */}
          {getLayout(<Component {...pageProps} />)}
          {/* </PrimaryLayout> */}
          <ToastContainer />
        </AuthProvider>
      </div>
    </>
  );
}

export default MyApp;
